### ISSUE TITLE
Missing method swe_get_library_path()

### ISSUE THREAD

**Issue by kevindecapite** [kevindecapite/php-sweph#1]
Was this excluded for any particular reason? I'm happy to add it in if you're accepting PRs, but I admit I've never worked on PHP extensions before.

**Comment by kevindecapite** [comment]
Thanks Joel, I just forked and added the PR for this. I rebuilt the `.so` file locally and it's working for me.

I'm curious, have you done much with this extension since you created it? I'd be curious to see what kind of PHP astrology site or app you've created :-)

**Comment by cyjoelchen** [comment]
Well done, thanks Kevin!

Please check my site: [Almuten](http://almuten.net). It's a chart casting/hosting service. It includes some interesting features like Chinese and Vedic astrology chart, celestial event calendar, transit timeline... etc. Register to see more features, it's totally free! :-)

**Comment by kevindecapite** [comment]
Thanks Joel, but I think you did the heavy lifting on this one :-)

I looked at your site briefly, looks like you're really making use of the SE. Feel free to keep in touch!
