### ISSUE TITLE
Does not compile on PhP 8

### ISSUE THREAD

**Issue by AstroSign-Dev** [kevindecapite/php-sweph#15]
It throws a lot of errors during make cmd because of stray instances of TSRMLS_CC macro. This macro was defined empty in PhP 7.x and removed in PhP 8.x

Cheers
Werner

**Comment by kevindecapite** [comment]
If we remove usage of this macro, older versions of PHP will no longer be supported by this library.

I think the best option will be to start tagging releases so we can document PHP version support and other changes more easily, which will also give anyone using this library more control over what they're installing.

If we move this direction, the next question is around naming conventions for tagging. Semantic versioning is probably the way to go, but we need to decide what constitutes version 1.0.0.

I suggest:

- 1.x.x versioning for pre-PHP 8.x support. This will allow us to continue to support the legacy PHP versions (including 7.x) by implementing bug fixes and non-breaking changes into php-sweph.
- 2.x.x. versioning for PHP 8.x support.

**Comment by AstroSign-Dev** [comment]
Thank you Kevin, and I fully aggree with your solution planning of different version numbers.
I found these hints:
https://www.seidengroup.com/2020/12/07/porting-extensions-to-php-8/ 
Scroll down to "RIP, Thread-Safe Resource Manager Macros"

**Comment by EsoCoding** [comment]
Just upgraded from php7.2 to 7.3.26 and can't compile now because of this TSRMLS error. To bad, guess i need to figure out how to solve this.

**Comment by kevindecapite** [comment]
It compiles just fine for me on PHP 7.3.25. I wouldn't expect one minor version update to make much of a difference.

**Comment by EsoCoding** [comment]
> It compiles just fine for me on PHP 7.3.25. I wouldn't expect one minor version update to make much of a difference.

I am a bit surprised to, but i guess it does..

[Screenshot](https://ibb.co/TcWL8hh)

**Comment by kevindecapite** [comment]
I just tested using my local Docker setup and it built fine in PHP 7.3.26. FWIW, I don't use this repository but the one I setup under my business' account. I actually want to reach out to Joel Chen about taking over the maintenance on this project.

In the meantime, here's a branch you can checkout to test with:

https://github.com/arcpointgroup/php-sweph/tree/php-7.3.26

Once checked out, just follow the instructions at the bottom of the README, which I'm copying here as well:

```
# From your local machine:
> docker-compose build
> docker-compose up
> docker exec -it se-php bash

# After `exec` you'll be in the container and can build the extension:
> ./go
```

**Comment by EsoCoding** [comment]
Ah i found the problem, seems php-8 got installed during a dist-upgrade... Thanx for the help.

**Comment by EsoCoding** [comment]
I am trying to compile php-sweph for php8. I removed all the TSRMLS_CC in sweph.c. After that i could compile and install. I have php-sweph running now, but still getting lots of php warnings from apache. Anyone already knows a solution?

```
PHP Warning:  Missing arginfo for swe_calc() in Unknown on line 0
PHP Warning:  Missing arginfo for swe_calc_ut() in Unknown on line 0
PHP Warning:  Missing arginfo for swe_fixstar() in Unknown on line 0
PHP Warning:  Missing arginfo for swe_fixstar_ut() in Unknown on line 0
PHP Warning:  Missing arginfo for swe_close() in Unknown on line 0
```
[https://stackoverflow.com/questions/66194531/how-to-compile-php-module-in-php8-0-that-used-to-use-tsrmls-cc-in-php7-but-is-d](url) 

But perhaps someone here already got is solved...?

**Comment by steve-rhodes** [comment]
Would be nice to see this working with PHP8 as support for 7.x gets dropped by end of year...

Does anyone have a working solution?

thanks

**Comment by AstroSign-Dev** [comment]
If you remove all occurrences of TSRMLS_CC from sweph.c and compile it after then it works with some minor function errors, but still with throwing all the missing arginfo warnings. It seems we have to find one who can give us a piece of example code on how to bring in these arginfo parts into sweph.c

**Comment by kevindecapite** [comment]
I have a vested interest in keeping this extension up to date with PHP and SE releases due to a business I'm building which depends upon it. I plan to make the extension PHP 8 compatible but am learning C as I go, so it's difficult for me to provide an ETA. I should have time this weekend to revisit it. Now that Mercury is retrograde, I think this may be the best time to review this again along with the other bugs the extension has.

**Comment by steve-rhodes** [comment]
thanks Kevin, that's great to hear! I still have to the end of the year before the pressure mounts to upgrade PHP... :)

**Comment by aloistr** [comment]
I will try to get the code in php-sweph/sweph.c compatible with both php7 and php8.
I have to find a #define constant which lets me determine the installed php version.
