### ISSUE TITLE
Two Constants for swe_rise_trans() usage are missing in sweph.c

### ISSUE THREAD

**Issue by AstroSign-Dev** [kevindecapite/php-sweph#19]
These two constants, which are used for jyotish calculations are still missing in sweph.c. It would be nice to have it in per default.

// ## Please Add these lines to the /* for swe_rise_transit() */ section into sweph.c 
REGISTER_LONG_CONSTANT("SE_BIT_GEOCTR_NO_ECL_LAT", SE_BIT_GEOCTR_NO_ECL_LAT , CONST_CS | CONST_PERSISTENT);
REGISTER_LONG_CONSTANT("SE_BIT_HINDU_RISING", SE_BIT_HINDU_RISING , CONST_CS | CONST_PERSISTENT);

**Comment by aloistr** [comment]
I have added them in my fork

**Comment by AstroSign-Dev** [comment]
Thank you, Alois
