### ISSUE TITLE
bug fixes for particular functions

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#21]
I fixed swe_rise_trans() so that it handles fixed star case correctly and returns the amended starname in the return hash

**Comment by kevindecapite** [comment]
I fixed this one as well and have a PR open for it:

https://github.com/cyjoelchen/php-sweph/pull/14

I was originally waiting on @cyjoelchen to merge and never merged it myself after he granted me collaborator access. Now I see there are conflicts. Did you apply the fix to `master` already?
