### ISSUE TITLE
Now on 2021-07-19 getting a make error on sweph.c

### ISSUE THREAD

**Issue by AstroSign-Dev** [kevindecapite/php-sweph#26]
/home/user/php-sweph/sweph.c: In function ‘zif_swe_jdut1_to_utc’:
/home/user/php-sweph/sweph.c:1559:5: error: ‘tjd_et’ undeclared (first use in this function); did you mean ‘tjd_ut’?
    &tjd_et, &gregflag) == FAILURE) {
     ^~~~~~
     tjd_ut
/home/ubu/php-sweph/sweph.c:1559:5: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:191: sweph.lo] Error 1

**Comment by aloistr** [comment]
Sorry for that, fixed now
