### ISSUE TITLE
Setup HTML docs on a Github pages site.

### ISSUE THREAD

**Issue by kevindecapite** [kevindecapite/php-sweph#29]
Now that we have inline documentation which is used to generate the `/doc/doc.html` file, it would be nice if this file was available for viewing publicly in the browser.

We should setup a Github pages site that loads this file as its homepage. The file will probably need to be renamed to `index.html`.

**Comment by aloistr** [comment]
I agree.

I tried to create a branch gh-pages, which is supposed to help that .html files appear as html, but it did not work.

Possible the owner of the repo must enable this, via Settings. The Settings menu seems not available to us.

Anyway, I think as  Almuten cyjoelchen is inactive, you should ask him to give you full admin permissions for the repo.
Then you can add Pages in Settings menu

**Comment by kevindecapite** [comment]
@cyjoelchen 

Would you grant me additional permissions on this repository and/or assist in creating a GH pages site whereby we can host the HTML docs publicly?

**Comment by kevindecapite** [comment]
Closing as I created a link to the markdown version of the docs in the README, which GitHub renders as HTML in the browser:

https://github.com/cyjoelchen/php-sweph/pull/65
