### ISSUE TITLE
swe_nod_aps_ut enforces incorrect parameter count.

### ISSUE THREAD

**Issue by kevindecapite** [kevindecapite/php-sweph#3]
Refs:
https://github.com/cyjoelchen/php-sweph/blob/master/sweph.c#L1820

Docs:
https://www.astro.com/swisseph/swephprg.htm#_Toc505244849

According to the official docs, the `swe_nod_aps_ut()` method only accepts 4 parameters. The PHP function, however, enforces 10 (see L1829).

To reproduce, call the method in the following 2 ways and notice the difference in output:

### With 4 parameters.
```
> swe_nod_aps_ut(2444342.6375, 2, SEFLG_SWIEPH, SE_NODBIT_MEAN)
Warning: Wrong parameter count for swe_nod_aps_ut() in php shell code on line 1
```

### With 10 parameters.
```
> swe_nod_aps_ut(2444342.6375, 2, SEFLG_SWIEPH, SE_NODBIT_MEAN, 1, 1, 1, 1, 1, 1)
Warning: swe_nod_aps_ut() expects exactly 4 parameters, 10 given in php shell code on line 1
```

I'm happy to make the change myself, but am not 100% sure how to do so. Other than changing L1829, what else is there to do?

**Comment by cyjoelchen** [comment]
Hi Kevin,
Yes, you are correct. Change the if(ZEND_NUM_ARGS() != 10) line will fix.

**Comment by kevindecapite** [comment]
Closing as this was fixed in the following commit:

https://github.com/cyjoelchen/php-sweph/commit/b721f5206aecffded4ecef74c71c065b0632c196
