### ISSUE TITLE
Make test ends with meaningless email question, how to suppress?

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#38]
at the end of make test I always get this meaningless email question

This report can be automatically sent to the PHP QA team at
http://qa.php.net/reports and http://news.php.net/php.qa.reports
This gives us a better understanding of PHP's behavior.
If you don't want to send the report immediately you can choose
option "s" to save it.  You can then email it to qa-reports@lists.php.net later.
Do you want to send this report now? [Yns]: n

how can I suppress it?

**Comment by kevindecapite** [comment]
I don't know but I believe it's there because PHP has its own official extensions so found bugs should be reported there if a contributor is working and happens to find one.

That said, if you use the Docker environment and `build-se` script, you at least won't have to answer the question, merely ignore it:

https://github.com/cyjoelchen/php-sweph/blob/master/build-se#L8

**Comment by aloistr** [comment]
The script build-se is not good for me, because make install requires me to be root, and I do not do development as root. 
I also do not know what Docker environment means. Have never used Docker.

**Comment by kevindecapite** [comment]
Docker is its own tool which requires installation and learning. Although not necessary at all for this project, it's a valuable tool for setting up ephemeral environments on any platform. It allows parity across all staging platforms: development, QA, production, etc.

At any extent, you should still be able to `yes n | make test` to auto-input an answer after the tests run.

**Comment by aloistr** [comment]
I created myself a script named fixtest
#!/bin/bash
sed -i 's/save_or_mail_results();//' run-tests.php

It removes a line from run-tests.php (which is recreated by phpize) so that no more mail questions get asked.
