### ISSUE TITLE
Pod documentation mismatch between tjd_ut and tjd_et

### ISSUE THREAD

**Issue by AstroSign-Dev** [kevindecapite/php-sweph#40]
Mismatch between parameter description (tjd_et) and parameters (tjd_ut) in function call

function swe_calc(tjd_ut, ipl, iflag)

Parameters

  double        tjd_et      Julian day in Ephemeris Time.

**Comment by kevindecapite** [comment]
This is fixed in `master` branch and will become part of the next release:

https://github.com/cyjoelchen/php-sweph/blob/master/swephp.c#L537
