### ISSUE TITLE
how to run in debugger

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#41]
I have compiled library swephp.so with debug on, and need to run a test script in gdb debugger.
How can I do this?

I have a problem with function swe_lun_occult_when_glob

**Comment by kevindecapite** [comment]
This may help. Unfortunately it's an archived article from a now defunct website so the page is riddled with ads:

https://www.programmersought.com/article/60081328612/

The "official" PHP internals online book offers much to be desired on this topic:

https://www.phpinternalsbook.com/php7/debugging.html

**Comment by AstroSign-Dev** [comment]
Maybe this helps also
https://willgallego.com/2018/04/16/a-101-on-debugging-php-internals-with-gdb/

**Comment by kevindecapite** [comment]
@AstroSign-Dev Very good find, thank you.

@aloistr I can debug with:

```
> gdb php
(gdb) run scratch.php
```

__scratch.php__

```
<?php
swe_set_ephe_path('./sweph/ephe');
echo "swe_lun_occult_when_glob for Venus\n";
$rv = swe_lun_occult_when_glob(2454466.5, SE_VENUS, "", SEFLG_SWIEPH, 0, 0);
var_dump($rv);
```

**Comment by aloistr** [comment]
thank you.
no need at the moment, issue resolved without debugger
