### ISSUE TITLE
zend_parse_parameters "d" delivers integer

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#43]
In gdb debugger, it lookks as if
if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "dldddl",
            &tjd_ut, &ifl, &geopos[0], &geopos[1], &geopos[2], &backward, &arg_len) == FAILURE) {
        return;
    }
delivers an integer value tjd_start=2454466 when my program calls 
swe_lun_eclipse_when(2454466.5, SEFLG_SWIEPH, 0, 0);

**Comment by kevindecapite** [comment]
I think you mean:
```
	if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "dlll",
			&tjd_start, &ifl, &ifltype, &backward, &arg_len) == FAILURE) {
		return;
	}
```
Anyway, even stranger is this:
```
(gdb) p tjd_start
$1 = 2454466
(gdb) p &tjd_start
$2 = (double *) 0x7fffffffae38
```
So `tjd_start` is indeed a double, but not parsing as such.

**Comment by aloistr** [comment]
I now think I have a bug in swephp.c which fucks up the stack or heap.
The problem does not appear in swe_calc* which I have updated to add tjd input value to output,
for test purposes

**Comment by kevindecapite** [comment]
You mean a bug elsewhere, not in function `swe_lun_eclipse_when()`?

**Comment by aloistr** [comment]
I do not know yet. I cannot continue now, maybe later tonight
Please run test swe_lun_eclipse.phpt and see whether you get the same truncated double tjd_start and tjd_ut

**Comment by kevindecapite** [comment]
Yes. It's truncated in all 3 method calls. And if I add a call to `swe_calc()` to that same test as well, `tjd_et` is returned correctly as you pointed out.

**Comment by aloistr** [comment]
bug fixed, wrong declaration of arg_len was the problem.

**Comment by kevindecapite** [comment]
For fix, see: https://github.com/cyjoelchen/php-sweph/pull/42/commits/7e3f9162d53ce2647786e9f9bc19d7ccfad0bf27
