### ISSUE TITLE
License information was missing

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#48]
License information was missing from the top level of this repo.

I have edited to Readme file and added a pointer to the license conditions, which are defined in the LICENSE file in the source directory sweph/src.

I pushed this to the master branch.

It should be noted that the GPL license as part of the dual licensing model has been replaced by Affero GPL (AGPL) since release 2.10.01 of Swiss Ephemeris.

The GPL license did not impose conditions on users, as long as they did not distribute software containing code or data from Swiss Ephemeris. Use on the server side did not impose any obligation to make source code accessible to others.

This has changed with AGPL. Now use on server side is subject to the conditions of AGPL. Alternatively, a user can purchase Astrodienst's professional license, under the dual licensing system for Swiss Ephemeris.

**Comment by kevindecapite** [comment]
> Now use on server side is subject to the conditions of AGPL.

I think that's a good change. Using the SE library server-side to run a proprietary application/website should require purchasing a license. Were you able to make this retroactive?

**Comment by aloistr** [comment]
No. But everybody will upgrade at some time. And anyway, Swiss Ephemeris does  not earn our living . Our reports do
