### ISSUE TITLE
Problem with zend_parse_parameters().

### ISSUE THREAD

**Issue by kevindecapite** [kevindecapite/php-sweph#5]
@cyjoelchen 

Hi Joel, I'm hoping you can offer some guidance on this issue I discovered.

I have found that the `swe_nod_aps()` and `swe_nod_aps_ut()` methods are not properly parsing the first parameter (`tjd_et` and `tjd_ut` respectively).

### TL;DR

These time values are not being treated as doubles but are somehow getting "truncated" to a lower integer value. Specifically, a `tjd_ut` input value of `2458625.2916628` is transforming into `2458624.000000` (examples below).

---

__Note that I've added 6 `fprintf()` debug statements to my branch. For testing purposes, you may want to check out my branch or add these statements into your local copy:__

1. https://github.com/kevindecapite/php-sweph/blob/fixing-swe-nod-aps/sweph.c#L1781
2. https://github.com/kevindecapite/php-sweph/blob/fixing-swe-nod-aps/sweph.c#L1788
3. https://github.com/kevindecapite/php-sweph/blob/fixing-swe-nod-aps/sweph.c#L1835
4. https://github.com/kevindecapite/php-sweph/blob/fixing-swe-nod-aps/sweph.c#L1842
5. https://github.com/kevindecapite/php-sweph/blob/fixing-swe-nod-aps/sweph.c#L1888
6. https://github.com/kevindecapite/php-sweph/blob/fixing-swe-nod-aps/sweph.c#L1895

I added these so I could look at the input parameters before and after the `zend_parse_parameters()` function call. Here are the results:

### `swe_nod_aps_ut()` doesn't work, but why?

```
php > print_r(swe_nod_aps_ut(2458625.2916628, 2, 258, 1));
swe_nod_aps_ut: tj=0.000000, ipl=0, iflag=2447376448, mthod=32563
swe_nod_aps_ut: tj=2458624.000000, ipl=2, iflag=258, mthod=1
Array
(
    [retflag] => 0
    [xnasc] => Array
        (
            [0] => 56.680931574465
            [1] => 3.0145592131883E-5
            [2] => 1.3220195603371
            [3] => 0.73612419649685
            [4] => -3.2429090376862E-5
            [5] => -0.00054243469771424
        )

    [xndsc] => Array
        (
            [0] => 67.564235606566
            [1] => 6.9195727311078E-5
            [2] => 0.57389584851169
            [3] => 1.675423329765
            [4] => -6.6127512121871E-5
            [5] => 0.002672750087396
        )

    [xnperi] => Array
        (
            [0] => 63.443414304512
            [1] => 0.80212500326375
            [2] => 1.3068768959424
            [3] => 0.73070414588612
            [4] => 0.80076160231545
            [5] => 0.00066077827187061
        )

    [xnaphe] => Array
        (
            [0] => 44.750484768039
            [1] => -2.7020123645768
            [2] => 0.58896673969793
            [3] => 1.694600935081
            [4] => -2.7071279397373
            [5] => -0.0013432826167913
        )

)
```

### `swe_deltat()` works, but why?

```
php > print_r(swe_deltat(2458625.2916628));
swe_deltat: tj=0.000000
swe_deltat: tj=2458625.291663
0.00080465229758673
```

Lastly, if you run `swetest` to query the same data, you can see how the values differ (`swetest` is correct, FYI):

```
swetest -bj2458625.2916628 -pe2 -fPfn -ut
date (dmy) 21.5.2019 greg.   18:59:59.666 UT		version 2.07.01
UT:  2458625.291662800     delta t: 69.521959 sec
TT:  2458625.292467453
Epsilon (true)    23°26' 8.8486
Nutation          -0° 0'17.2589   -0° 0' 3.4782
name            peri apo nodAsc nodDesc
Mercury          64.4017370  46.8392201  57.3279454  57.6318570  69.7186353
```

**Comment by cyjoelchen** [comment]
Hi Kevin,
I'm looking into this. It's strange. Seems only swe_nod_aps() and swe_nod_aps_ut() cannot parse the double parameter correctly...

**Comment by cyjoelchen** [comment]
Kevin, I just pushed the fix of issue #3 and #5. Let me know if it's good to close.
Thanks, Joel.

**Comment by kevindecapite** [comment]
Thank you, Joel... so far this fix seems to have resolved the issue. Makes sense as there was a type mismatch so I assume a memory allocation issue?

**Comment by kevindecapite** [comment]
Closing as this was fixed in the following commit:

https://github.com/cyjoelchen/php-sweph/commit/b721f5206aecffded4ecef74c71c065b0632c196
