### ISSUE TITLE
Experimental doc .md files

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#63]
In branch documentation, ./sweph/doc
I am experimenting with .md files created via pandoc -f docx -t markdown from the original Swisseph docx files.
The results need manual work, for tabular data elements 
It is an experiment, into which I can only invest minimal time.
I want to find out whether we should move from Word to markdown  as fundamental maintenance firmat.

**Comment by kevindecapite** [comment]
> I want to find out whether we should move from Word to markdown as fundamental maintenance firmat.

Do you mean for the main SE library? I would vote 100% yes to use markdown, but that would be a big endeavor to convert it all to that format. The advantages are many, however:

- Plain-text file format is readable on all systems w/o requiring additional software.
- Markdown is "human-readable" as-is, in plain-text, and does not need to be parsed/interpreted.
- It's ubiquitously supported almost everywhere now (Github, project management systems, phone apps, et al.).
- It supports all needed types of formatting, including code and tables.

__Sample Table__

```
| House | Chart A             | Chart B             | Midpoint               |
| ----- | ------------------- | ------------------- | ---------------------- |
| 1st   | 19&deg; Aquarius    | 13&deg; Virgo       | __1&deg; Sagittarius__ |
| 2nd   | 27&deg; Aries       | 8&deg; Libra        | __17&deg; Cancer__     |
| 3rd   | 27&deg; Taurus      | 7&deg; Scorpio      | __17&deg; Leo__        |
| 4th   | 16&deg; Gemini      | 11&deg; Sagittarius | __13&deg; Virgo__      |
| 5th   | 1&deg; Cancer       | 15&deg; Capricorn   | __8&deg; Libra__       |
| 6th   | 18&deg; Cancer      | 16&deg; Aquarius    | __2&deg; Taurus__      |
| 7th   | 19&deg; Leo         | 13&deg; Pisces      | __1&deg; Gemini__      |
| 8th   | 27&deg; Libra       | 8&deg; Aries        | __17&deg; Capricorn__  |
| 9th   | 27&deg; Scorpio     | 7&deg; Taurus       | __17&deg; Aquarius__   |
| 10th  | 16&deg; Sagittarius | 11&deg; Gemini      | __13&deg; Pisces__     |
| 11th  | 1&deg; Capricorn    | 15&deg; Cancer      | __8&deg; Aries__       |
| 12th  | 18&deg; Capricorn   | 16&deg; Leo         | __2&deg; Scorpio__     |
```

That table was copy-pasted from the documentation I'm creating for my software:
https://docs.lunaastrology.com/interact/composite-charts/#select-the-midpoint-base

In fact, that documentation is 100% markdown, powered by this free tool:
https://squidfunk.github.io/mkdocs-material/

It is also hosted on Github pages.

**Comment by astrorigin** [comment]
I had planned to transfer a large part of the swisseph documentation into reStructuredText format (rst), to use with my software (using [Sphinx](https://www.sphinx-doc.org/)).
RST is generally better suited than markdown for technical documentation, and is supported by Github. If interested, I could go ahead and do that for the C API.

**Comment by aloistr** [comment]
I looked into rst and Sphinx.
For my modest purposes, I think md (Markdown) is preferable.
Its syntax is simpler, and it is sufficient.
It seems to have simple markup cide to get for example blocks of C code or Perl code shown with syntax highlighting.
In branch documentation, directory sweph/doc are sample .md files which I have begun editing a bit.
Look in swephprg.md at the swemini.c sample code near the top, or in swisseph.md at the table of ephemeris files.

For me at Astrodienst it is also important that we have a lot of internal memos created since 1987, which are our continuous  inhouse documentation.
They are pure text, we had already gwo years ago discussed internally to move to markdown.

A single consistent format method is desirable for us.

md can also be used for Perl code highlighting with the ```perl directive. rst and Sphinx lack a Perl extension.

Because Astrodienst continues to remain Perl based, this is a relevant point for us.

**Comment by astrorigin** [comment]
I've checked and Sphinx supports Perl syntax-highlighting. https://pygments.org/languages/

(Perl documentation is probably usually served with perldoc/pod anyway)

**Comment by aloistr** [comment]
I have decided the issue.
At Astrodienst, we move to Markdown (Github flavour) for future maintenance of the Swiss Ephemeris documention.
The conversion is in progress, I do the work with the Typora editor on a Mac, with assistance from vi for conversion of existing tables.
