### ISSUE TITLE
Incoherent returned flags for swe_get_ayanamsa_ex(_ut) ?

### ISSUE THREAD

**Issue by astrorigin** [kevindecapite/php-sweph#71]
Looking at the test files for functions `swe_get_ayanamsa_ex` and `swe_get_ayanamsa_ex_ut`, we can see that the returned flags (`rc` value) is 66, meaning: `SEFLG_SWIEPH | SEFLG_NONUT`,
however `SEFLG_NONUT` was not given in `iflag`.

Passing `SEFLG_SWIEPH | SEFLG_NONUT` yields a different daya value, and correctly returns 66 as `rc` value.

(Same goes in Python.)

Is it correct to assume that `rc` value indicates what kind of computation was done, or not ?

**Comment by aloistr** [comment]
Has been fixed in php-sweph branch issues/71 and in Swisseph repo branch devel

**Comment by aloistr** [comment]
Ps: the ayanamsha returned was correct, only the returned  flag was wrong.

**Comment by aloistr** [comment]
Ps: I also improved the test cases, removed irrelevant flag SEFLG_SPEED, made two variant calls with and without nutation
