### ISSUE TITLE
split hour in swe_revjul, allow missing gregflag in swe_julday amd swe_revjul

### ISSUE THREAD

**Issue by aloistr** [kevindecapite/php-sweph#77]
Running the command line samples in perl-sweph (see Swiss Ephemeris mailing list) I noticed that perl-sweph::swe_revjul() also separates the double dhou into
ihou
imin
isec
dsec

that comes handy, as the caller will often want to get minutes and seconds.

Could be added in php-sweph::swe_revjul as well.

perl swe_revjul() and swe_julday() also tolerate missing parameter gregflag, and default to Gregorian. 
php-sweph might do that as well, in swe_julday and swe_revjul.

**Comment by AstroSign-Dev** [comment]
appreciated, very good idea
