### ISSUE TITLE
phpize issue

### ISSUE THREAD

**Issue by sskohli01** [kevindecapite/php-sweph#8]
On my mac, phpize is not working
$phpize 
grep: /usr/include/php/main/php.h: No such file or directory
grep: /usr/include/php/Zend/zend_modules.h: No such file or directory
grep: /usr/include/php/Zend/zend_extensions.h: No such file or directory
Configuring for:
PHP Api Version:        
Zend Module Api No:     
Zend Extension Api No:  
/usr/local/bin/autoconf: /usr/local/bin/autom4te: /Applications/XAMPP/xamppfiles/bin/perl: bad interpreter: No such file or directory
/usr/local/bin/autoconf: line 505: /usr/local/bin/autom4te: Undefined error: 0

php -v
PHP 7.1.33 (cli) (built: Jan  6 2020 22:21:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by AstroSign-Dev** [comment]
This has nothing to do with sweph, it is a Mac issue. You can go through this thread
https://github.com/phpredis/phpredis/issues/1654 
Cheers
Werner

**Comment by aloistr** [comment]
I have tried to run it on my Mac, and I fail in make because include fiks are not found.
I have made a copy of /usr/bin/phpize to /usr/local/bin and modified the includedir path, but that helps nothing.
After phpize --clean, phpize, configure
make still fails with not found include files issues.
Clear instructions how to proceed on Mac would be welcome.
Not so much for me, my work environment is Linux, but for many users

**Comment by AstroSign-Dev** [comment]
# MacOS (Intel): setup of swetest and sweph.so with PHP8
// created and tested 2021-07-18 on MacOS BigSur 11.4 by Werner Helbig - AstroSign
// will be renewed and added to readme.md when php-sweph compiling is compatible with PHP 8

// Prerequisite: XCode, VSCode and Homebrew are already installed and updated

cd ~

// If not already installed, you can do Homebrew with sh command provided from Homebrew at: https://brew.sh
//  If not already installed, Direct Visual Studio Code download from Microsoft: https://go.microsoft.com/fwlink/?LinkID=534106 or install with homebrew (path setting included): 
brew install --cask visual-studio-code

// Verify xcode developer command line tools are installed and if not install it: xcode-select —install
xcode-select --version
// Output on my Mac:
xcode-select version 2384.

php -v
// Output on Mac OS Big Sur 11.4:
// WARNING: PHP is not recommended
// PHP is included in macOS for compatibility with legacy software.
// Future versions of macOS will not include PHP.
// PHP 7.3.24-(to be removed in future macOS) (cli) (built: May  8 2021 09:40:37) ( NTS )
// Copyright (c) 1997-2018 The PHP Group
// Zend Engine v3.3.24, Copyright (c) 1998-2018 Zend Technologies

brew install php
// Output excerpt from brew install php:
// ==> Summary
//  /usr/local/Cellar/php/8.0.8_1: 500 files, 77.9MB
// ==> Caveats
// ==> php
// To enable PHP in Apache add the following to httpd.conf and restart Apache:
//    LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so
//
//   <FilesMatch \.php$>
//        SetHandler application/x-httpd-php
//    </FilesMatch>
//
// Finally, check DirectoryIndex includes index.php
//    DirectoryIndex index.php index.html
//
// The php.ini and php-fpm.ini file can be found in:
//    /usr/local/etc/php/8.0/
//
// To start php:
//  brew services start php
// Or, if you don't want/need a background service you can just run:
//   /usr/local/opt/php/sbin/php-fpm --nodaemonize
//

// after php install finished, close shell window and reopen a new one, you should now have PHP 8 installed and can verify with:
php -v
// Output:
// PHP 8.0.8 (cli) (built: Jul 12 2021 11:13:36) ( NTS )
// Copyright (c) The PHP Group
// Zend Engine v4.0.8, Copyright (c) Zend Technologies
//    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies


git clone https://github.com/cyjoelchen/php-sweph.git
cd php-sweph
ls -la

// Until we fixed it for PHP 8 usage we have to remove all occurrencies of TSRMLS_CC in sweph.c.
// I do this with VS Code, EDIT —> REPLACE —> Find —> TSRMLS_CC   
// Let REPLACE field empty and —> Enter
code .
// Save file and close VSCode

phpize
./configure
make
sudo make install

// Output from last command:
// Installing shared extensions:     /usr/local/Cellar/php/8.0.8_1/pecl/20200930/

ls -las /usr/local/Cellar/php/8.0.8_1/pecl/20200930/
// Output file:
// 1552 -rwxr-xr-x  1 root       admin  792248 18 Jul 11:25 sweph.so

php -i | grep extension_dir
// Output: extension_dir => /usr/local/lib/php/pecl/20200930 => /usr/local/lib/php/pecl/20200930

// Check if sweph.so is in this path
ls -las /usr/local/lib/php/pecl/20200930

// check location of loaded php.ini file and put sweph.so into the extension section
php -i | grep php.ini
// Output:
// Configuration File (php.ini) Path => /usr/local/etc/php/8.0
// Loaded Configuration File => /usr/local/etc/php/8.0/php.ini
nano /usr/local/etc/php/8.0/php.ini
// In nano I searched with Ctrl+W for sqlite3 and then after that line I put in a new line with entry: extension=sweph
// Ctrl+X to close and Y —> Enter to save the php.ini file

// with php -m we can now see that the extension sweph.so is loaded, and on PHP8 with php -m | grep sweph 
// we can see all the missing arginfo we have to implement, but it still works with these warnings

// download the swiss ephemeris files you want to use into a directory of your choice
// for this demo I put it into the \~/sweph directory (~ = in my case: /Users/astrosign/sweph)
// we can now use this path as a source in the example code in the ~/php-sweph/example.php file
// I exchanged line 3 in example.php file: swe_set_ephe_path("/usr/local/share/sweph");
// with: swe_set_ephe_path("/Users/astrosign/sweph");
// we are still in the php-sweph folder and we can now execute the example file example.php with:

php example/example.php
// You can see now after all the Warning Messages (yes, will be eliminated in future versions) the output of the example code like:
// planets:
//{
//    "julday": 2459413.9250694443,
//    "0": {
//        "name": "Sun",
//        "lng": 116.01447350917503,
//        "lat": 0.00013252088021640002,
//        "speed": 0.9540942479415587
//    },

// This confirms the sweph.so PHP extension is working (with some minor warnings), and we can use it on MacOS for testing purposes

// Now we compile swetest and copy it to our already existing sweph folder, we put it then into $PATH variable also to be able to use it from our home directory without a leading dot

cd ~/php-sweph/sweph/src
make
cp ~/php-sweph/sweph/src/swetest ~/sweph/swetest
cd ~/sweph
./swetest -eswe -b18.07.2021 -geopos8.54,47.38 -ut11:00 -fPLls -p0142536m -sid27

// Output:
// ./swetest -edir/Users/astrosign/sweph -eswe -b18.07.2021 -geopos8.54,47.38 -ut11:00 -fPLls -p0142536m -sid27
// date (dmy) 18.7.2021 greg.   11:00:00 UT		version 2.10.01a
// UT:  2459413.958333333     delta t: 69.286670 sec
// TT:  2459413.959135263   ayanamsa =   24° 8'15.5241 (True Citra)
// geo. long 8.540000, lat 47.380000, alt 0.000000
// Epsilon (m)       23°26'11.3155
// Sun               91°54'30.8335  91.9085649   0.9541523
// Moon             195°29'26.0593  195.4905720  14.1930630
// Mars             118°43'48.9609  118.7302669   0.6243053
// Mercury           76°38' 1.8940  76.6338594   1.8241074
// Jupiter          306°50' 3.0898  306.8341916  -0.0843854
// Venus            121°34'26.5146  121.5740318   1.2033372
// Saturn           287° 7'36.9125  287.1269201  -0.0701975
// mean Node         44°12'42.3913  44.2117754  -0.0528973

// put sweph directory into path:
cd ~
echo $PATH
// Output: /Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

// Now we add location of swetest (in this case: /Users/astrosign/sweph) as a permanent path, we have to add this into the .zshrc file:
// export PATH=$PATH:/Users/astrosign/sweph

nano ~/.zshrc

// activate new path
. ~/.zshrc

echo $PATH
// Output: /Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/astrosign/sweph

// Now we can execute from our homedirectory and without the leading dot, in other words: finished setting up swetest and sweph.so on MacOS
swetest -edir/Users/astrosign/sweph -eswe -b18.07.2021 -geopos8.54,47.38 -ut11:00 -fPLls -p0142536m -sid27

**Comment by kevindecapite** [comment]
@AstroSign-Dev 

Hello Werner, I hope you are well. Since you have already written the instructions for installing this extension on macOS, would you be willing to add them to the README?

1. Fork this repo if you haven't yet.
2. Create a new branch and commit your changes to it.
3. Push the branch to your fork and open a PR.

I will test by copying/pasting your instructions step-by-step on my Mac to verify it works as expected. Since I use Docker for all development work, my Mac is in a "factor default" state with regards to PHP so it will make for a good test environment I think.

Cheers.

__Edit:__
I should add that PHP 8 compatibility is now ready, pending final review.

**Comment by AstroSign-Dev** [comment]
Ok, but this will need some time (we have nice weather here ;-) ), because I have to setup one of my Intel MacBooks from scratch with PHP8 and try to comment it from the beginning in Markdown format. I will compile then swephp.so as well as swetest send the result by email and you can then upload it. I will also try to do as you mentioned above, but I am not a GitHub hero yet, but I will try and learn :-). As soon as the new 2021 MacBooks with M1 are coming out this year, I will test on that also.

@aloistr & @kevindecapite 
Thank you for all your hard work to get this up and running on PHP7 & especially on PHP8

Cheers

**Comment by kevindecapite** [comment]
@AstroSign-Dev There is no rush and if you would like to learn more about forking and so forth in Github, we can setup a call to walk through it together. Enjoy your summer in the meantime.

**Comment by aloistr** [comment]
I am trying to build php-sweph on Mac Catalina
php -v
PHP 7.3.11 (cli) (built: Jun  5 2020 23:50:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies

After fixing Makefile via trial and error (dif not find some .h files) to have
INCLUDES = -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/Users/alois/php-sweph-4.0.0/sweph/src -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php/main -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php/Zend -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php/TSRM

Now the compile fails with 

/Users/alois/php-sweph-4.0.0/swephp.c:1082:45: error: too few arguments provided to
      function-like macro invocation
        add_assoc_string(return_value, "serr", serr);
                                                   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php/Zend/zend_API.h:393:9: note: 
      macro 'add_assoc_string' defined here
#define add_assoc_string(__arg, __key, __str, __duplicate) add_assoc_string_ex...

**Comment by AstroSign-Dev** [comment]
@aloistr did you install homebrew?

I just tested on MacOS BigSur with version 4 and there it works, the only thing is that 2 functions are showing FAIL executing make test.
**_These are: FAIL Basic test [tests/swe_azalt_refrac.phpt] and FAIL Basic test [tests/swe_fixstar.phpt], all others are PASS_**

My environment is MacOS BigSur version 11.5.1, brew is updated, php 8 is installed

xcode-select --version
xcode-select version 2384

php -v
PHP 8.0.9 (cli) (built: Jul 29 2021 17:21:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.9, Copyright (c), by Zend Technologies

sudo make install
Password:
Installing shared extensions:     /usr/local/Cellar/php/8.0.9/pecl/20200930/

ls -la /usr/local/Cellar/php/8.0.9/pecl/20200930/ | grep swephp
-rwxr-xr-x  1 root       admin  707288 13 Aug 14:11 swephp.so

and swetest gives:
swetest -edir/Users/astrosign/sweph -eswe -b13.08.2021 -geopos8.54,47.38 -fPLls -p0142536m -sid27
date (dmy) 13.8.2021 greg.   0:00:00 TT		version 2.10.02
UT:  2459439.499198158     delta t: 69.279171 sec
TT:  2459439.500000000   ayanamsa =   24° 8'11.1025 (True Citra)
geo. long 8.540000, lat 47.380000, alt 0.000000
Epsilon (m)       23°26'11.2827
Sun              116°20'36.8169  116.3435603   0.9602700
Moon             171°53'53.6645  171.8982402  13.8897976
Mars             134°46'22.3409  134.7728725   0.6324693
Mercury          127°52' 0.2345  127.8667318   1.8331285
Jupiter          304° 0'25.8227  304.0071730  -0.1288581
Venus            152° 5'29.3060  152.0914739   1.1854959
Saturn           285°15'22.9243  285.2563679  -0.0722095
mean Node         42°51'38.3470  42.8606520  -0.0529064

**Comment by aloistr** [comment]
I am not sure why you report swetest.
swetest has nothing to do with php.

**Comment by AstroSign-Dev** [comment]
It is that if you created swephp.so on Mac there could also be the neccessity to have a working copy of swetest also, at least in my case. So if you have already downloaded all the source files, then why not compile and use that for short tests also?

Cheers
Werner

________________________________
Von: Alois Treindl ***@***.***>
Gesendet: Friday, August 13, 2021 5:25:13 PM
An: cyjoelchen/php-sweph ***@***.***>
Cc: Werner Helbig (AstroSign) ***@***.***>; Mention ***@***.***>
Betreff: Re: [cyjoelchen/php-sweph] phpize issue (#8)


I am not sure why you report swetest.
swetest has nothing to do with php.

**Comment by kevindecapite** [comment]
Instructions for macOS Big Sur installation are now in the Wiki:
https://github.com/cyjoelchen/php-sweph/wiki/Install-on-macOS-Big-Sur.
