### ISSUE TITLE
When using the jpl de431.eph some values are not set

### ISSUE THREAD

**Issue by blucobalto** [kevindecapite/php-sweph#80]
**Describe the bug**
When using the jpl de431.eph some values are not set.
I am using the example in Readme.md
Use SEFLG_JPLEPH || SEFLG_SPEED;
In the return array of planetary data the dimensions 3, 4, 5 are not valued;

**To Reproduce**
1. set: SEFLG_JPLEPH || SEFLG_SPEED
2. swe_set_ephe_path ("./sweph/ephe"); //for me
3. swe_set_jpl_file ("de431.eph");  //for me
2. Date and Hour: 2021/11/01 17:00:00
3. See values

**Expected behavior**

**With SEFLG_SPEED**:
    "julday": 2459520.2083333335,
    "0": {
        "0": 219.48769346485267,
        "1": 6.167648920321542e-5,
        "2": 0.9924469626090567,
        "3": 1.0008847453654508,
        "4": -1.9935282494445833e-5,
        "5": -0.0002532148272806739,
        "serr": "",
        "rc": 258
    },
    "1": {
        "0": 176.38730256037078,
        "1": 4.781276302406268,
        "2": 0.0024963818084878624,
        "3": 13.964784159645811,
        "4": -0.528824526366118,
        "5": -3.9819746948354696e-5,
        "serr": "",
        "rc": 258
    },
    "2": {
        "0": 203.44184090562658,
        "1": 2.0442185461269946,
        "2": 1.1682872169599843,
        "3": 1.4979756689684907,
        "4": -0.04530736989453414,
        "5": 0.021981241196193605,
        "serr": "",
        "rc": 258
    },
   .................

**With JPL DE431.eph  (SEFLG_JPLEPH || SEFLG_SPEED)**
    "julday": 2459520.2083333335,
    "0": {
        "0": 219.4876933828836,
        "1": 6.165079464200357e-5,
        "2": 0.9924469597778867,
        "3": 0,
        "4": 0,
        "5": 0,
        "serr": "",
        "rc": 1
    },
    "1": {
        "0": 176.38730252640642,
        "1": 4.781276296811643,
        "2": 0.0024963818121133997,
        "3": 0,
        "4": 0,
        "5": 0,
        "serr": "",
        "rc": 1
    },
    "2": {
        "0": 203.4418408023076,
        "1": 2.044218528194945,
        "2": 1.1682872149149703,
        "3": 0,
        "4": 0,
        "5": 0,
        "serr": "",
        "rc": 1
    },
    .................
Thanks a lot,
Blu

**Comment by aloistr** [comment]
I am not fluent in php syntax, but think it must ,like in C, be 
SEFLG_JPLEPH | SEFLG_SPEED and not ||

With Moshier and Swisseph, speed is always returned, even when not correctly requested, because it is there anyway.

In jpl mode it must be computed specifically and is only provided if correctly requested. 
Personally, I would not use jpl mode, is has zero advantages.

**Comment by blucobalto** [comment]
Ops! You're right. 
SEFLG_JPLEPH | SEFLG_SPEED; // is the correct statement. 
The values are calculated correctly.

Thanks a lot,
Blu
