### ISSUE TITLE
Stub file for phpstorm IDE

### ISSUE THREAD

**Issue by AstroSign-Dev** [kevindecapite/php-sweph#81]
Kevin, is it possible for you to create and register a stub file for swephp, so that the functions of swephp are recognized by phpstorm? See [phpstorm-stubs](https://github.com/JetBrains/phpstorm-stubs) on github.

**Comment by kevindecapite** [comment]
Hi Werner, can we not use this?

https://github.com/cyjoelchen/php-sweph/blob/master/swephp.stub.php

It's a stub I wrote which is converted into the relevant `*_arginfo.h` files by this library:

https://github.com/nikic/PHP-Parser

**Comment by kevindecapite** [comment]
@AstroSign-Dev 

I setup a plugin repository for maintaining PhpStorm support for the SE extension:

https://github.com/arcpointgroup/phpstorm-library-plugin

You only need to follow the installation instructions which are very basic:
- Download the JAR file.
- Install it into PhpStorm & restart.

__Notes:__
- The constants are not in the stub so they are still unfound in the IDE.
- The stub is required by the extension for PHP 8 support; I would like that to be the "source of the truth" for the stub file and advocate for copy-pasting updated stub file(s) into the plugin repository as needed.
