### ISSUE TITLE
Undeclared function error with PHP 5.4

### ISSUE THREAD

**Issue by gman213** [kevindecapite/php-sweph#82]
We've tried v2.0.29
We are getting the following error on installing with PHP 5.4 

"/bin/sh /root/php-sweph/libtool --mode=compile cc  -I. -I/root/php-sweph -DPHP_ATOM_INC -I/root/php-sweph/include -I/root/php-sweph/main -I/root/php-sweph -I/opt/cpanel/ea-php54/root/usr/include/php -I/opt/cpanel/ea-php54/root/usr/include/php/main -I/opt/cpanel/ea-php54/root/usr/include/php/TSRM -I/opt/cpanel/ea-php54/root/usr/include/php/Zend -I/opt/cpanel/ea-php54/root/usr/include/php/ext -I/opt/cpanel/ea-php54/root/usr/include/php/ext/date/lib -I/root/php-sweph/sweph/src  -DHAVE_CONFIG_H  -g -O2   -c /root/php-sweph/sweph.c -o sweph.lo
libtool: compile:  cc -I. -I/root/php-sweph -DPHP_ATOM_INC -I/root/php-sweph/include -I/root/php-sweph/main -I/root/php-sweph -I/opt/cpanel/ea-php54/root/usr/include/php -I/opt/cpanel/ea-php54/root/usr/include/php/main -I/opt/cpanel/ea-php54/root/usr/include/php/TSRM -I/opt/cpanel/ea-php54/root/usr/include/php/Zend -I/opt/cpanel/ea-php54/root/usr/include/php/ext -I/opt/cpanel/ea-php54/root/usr/include/php/ext/date/lib -I/root/php-sweph/sweph/src -DHAVE_CONFIG_H -g -O2 -c /root/php-sweph/sweph.c  -fPIC -DPIC -o.libs/sweph.o
/root/php-sweph/sweph.c: In function 'zif_swe_calc':
/root/php-sweph/sweph.c:571:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:571:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c:571:2: note: each undeclared identifier is reported only once for each function it appears in
/root/php-sweph/sweph.c: In function 'zif_swe_calc_ut':
/root/php-sweph/sweph.c:622:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:622:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_calc_pctr':
/root/php-sweph/sweph.c:674:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:674:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_fixstar':
/root/php-sweph/sweph.c:731:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "star", star);
                                             ^
/root/php-sweph/sweph.c:731:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "star", star);
  ^
/root/php-sweph/sweph.c:732:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c: In function 'zif_swe_fixstar_ut':
/root/php-sweph/sweph.c:786:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "star", star);
                                             ^
/root/php-sweph/sweph.c:786:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "star", star);
  ^
/root/php-sweph/sweph.c:787:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c: In function 'zif_swe_get_planet_name':
/root/php-sweph/sweph.c:920:20: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(name);
                    ^
/root/php-sweph/sweph.c:920:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(name);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_get_ayanamsa_ex':
/root/php-sweph/sweph.c:1076:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:1076:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_get_ayanamsa_ex_ut':
/root/php-sweph/sweph.c:1163:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:1163:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_get_ayanamsa_name':
/root/php-sweph/sweph.c:1196:52: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(swe_get_ayanamsa_name((int)isidmode));
                                                    ^
/root/php-sweph/sweph.c:1196:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(swe_get_ayanamsa_name((int)isidmode));
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_version':
/root/php-sweph/sweph.c:1225:33: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(swe_version(name));
                                 ^
/root/php-sweph/sweph.c:1225:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(swe_version(name));
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_get_library_path':
/root/php-sweph/sweph.c:1253:45: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
     RETURN_STRING(swe_get_library_path(path));
                                             ^
/root/php-sweph/sweph.c:1253:5: error: 'RETURN_STRING' undeclared (first use in this function)
     RETURN_STRING(swe_get_library_path(path));
     ^
/root/php-sweph/sweph.c: In function 'zif_swe_get_current_file_data':
/root/php-sweph/sweph.c:1311:43: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "path", a);
                                           ^
/root/php-sweph/sweph.c:1311:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "path", a);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_utc_to_jd':
/root/php-sweph/sweph.c:1633:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:1633:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_houses_ex2':
/root/php-sweph/sweph.c:1932:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:1932:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_houses_armc_ex2':
/root/php-sweph/sweph.c:2085:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:2085:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_house_pos':
/root/php-sweph/sweph.c:2147:21: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
   RETURN_STRING(serr);
                     ^
/root/php-sweph/sweph.c:2147:3: error: 'RETURN_STRING' undeclared (first use in this function)
   RETURN_STRING(serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_house_name':
/root/php-sweph/sweph.c:2190:20: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(name);
                    ^
/root/php-sweph/sweph.c:2190:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(name);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_gauquelin_sector':
/root/php-sweph/sweph.c:2220:21: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
   RETURN_STRING(serr);
                     ^
/root/php-sweph/sweph.c:2220:3: error: 'RETURN_STRING' undeclared (first use in this function)
   RETURN_STRING(serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_sol_eclipse_where':
/root/php-sweph/sweph.c:2251:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2251:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_lun_occult_where':
/root/php-sweph/sweph.c:2293:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2293:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_sol_eclipse_how':
/root/php-sweph/sweph.c:2334:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2334:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_sol_eclipse_when_loc':
/root/php-sweph/sweph.c:2370:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2370:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_lun_occult_when_loc':
/root/php-sweph/sweph.c:2414:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2414:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_sol_eclipse_when_glob':
/root/php-sweph/sweph.c:2454:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2454:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_lun_occult_when_glob':
/root/php-sweph/sweph.c:2493:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2493:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_lun_eclipse_how':
/root/php-sweph/sweph.c:2529:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2529:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_lun_eclipse_when':
/root/php-sweph/sweph.c:2565:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2565:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_lun_eclipse_when_loc':
/root/php-sweph/sweph.c:2601:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2601:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_pheno':
/root/php-sweph/sweph.c:2642:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2642:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_pheno_ut':
/root/php-sweph/sweph.c:2678:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2678:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_rise_trans':
/root/php-sweph/sweph.c:2826:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2826:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c:2835:47: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
    add_assoc_string(return_value, "star", star);
                                               ^
/root/php-sweph/sweph.c: In function 'zif_swe_rise_trans_true_hor':
/root/php-sweph/sweph.c:2871:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2871:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c:2880:47: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
    add_assoc_string(return_value, "star", star);
                                               ^
/root/php-sweph/sweph.c: In function 'zif_swe_nod_aps':
/root/php-sweph/sweph.c:2909:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2909:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_nod_aps_ut':
/root/php-sweph/sweph.c:2961:46: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
   add_assoc_string(return_value, "serr", serr);
                                              ^
/root/php-sweph/sweph.c:2961:3: error: 'add_assoc_string' undeclared (first use in this function)
   add_assoc_string(return_value, "serr", serr);
   ^
/root/php-sweph/sweph.c: In function 'zif_swe_deltat_ex':
/root/php-sweph/sweph.c:3025:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:3025:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_time_equ':
/root/php-sweph/sweph.c:3047:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:3047:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_lmt_to_lat':
/root/php-sweph/sweph.c:3070:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:3070:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_lat_to_lmt':
/root/php-sweph/sweph.c:3092:45: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
  add_assoc_string(return_value, "serr", serr);
                                             ^
/root/php-sweph/sweph.c:3092:2: error: 'add_assoc_string' undeclared (first use in this function)
  add_assoc_string(return_value, "serr", serr);
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_cs2timestr':
/root/php-sweph/sweph.c:3389:70: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(swe_cs2timestr((int)t, (int)sep, (int)suppressZero, a));
                                                                      ^
/root/php-sweph/sweph.c:3389:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(swe_cs2timestr((int)t, (int)sep, (int)suppressZero, a));
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_cs2lonlatstr':
/root/php-sweph/sweph.c:3407:63: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(swe_cs2lonlatstr((int)t, pchar[0], mchar[0], s));
                                                               ^
/root/php-sweph/sweph.c:3407:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(swe_cs2lonlatstr((int)t, pchar[0], mchar[0], s));
  ^
/root/php-sweph/sweph.c: In function 'zif_swe_cs2degstr':
/root/php-sweph/sweph.c:3422:40: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(swe_cs2degstr((int)t, a));
                                        ^
/root/php-sweph/sweph.c:3422:2: error: 'RETURN_STRING' undeclared (first use in this function)
  RETURN_STRING(swe_cs2degstr((int)t, a));
  ^
make: * [sweph.lo] Error 1"

**The config file in v2.0.29 is incompatible with PHP 5.4. I can configure  v2.0.29 with PHP 7.4 but not 5.4. But since our website is in 5.4, we are stuck.**

**Comment by hostingshades-nitin** [comment]
the same issue with version 4
Is there any guide we can compile this module with PHP 5.4?


we can easily compile the code with PHP 7.4 but not with php5.4

**Comment by kevindecapite** [comment]
> We've tried v2.0.29

Have you tried this release?
- https://github.com/cyjoelchen/php-sweph/releases/tag/3.1.0

**Comment by kevindecapite** [comment]
Closing as PHP 5.4 is not supported by this extension.
