### ISSUE TITLE
PHP 8.1 deprecation warnings break tests

### ISSUE THREAD

**Issue by nosilentesdblog** [kevindecapite/php-sweph#85]
**Describe the bug**
The PHP 8.1 depcrecation warnings of `Passing null to non-nullable internal function parameter` is breaking the two tests `swe_get_library_path` and `swe_set_ephe_path`. The reason for this is that the deprecation warnings are treated as strings when calling the functions and thus are part of the test assertions.

**To Reproduce**
1. Call `make test`

**Expected behavior**
Passing tests and not treating PHP deprecation warnings as part of input/output in assertions.

**Environment:**
 - PHP 8.1 fpm container from docker hub

**Comment by kevindecapite** [comment]
Thank you for posting this. I should have time to fix this later today. It looks like `swe_set_ephe_path()` should support `null` as an input parameter. So the extension will need to be updated accordingly.

https://github.com/cyjoelchen/php-sweph/blob/master/sweph/src/sweph.c#L1373

**Comment by kevindecapite** [comment]
This issue has been fixed and released here:
- https://github.com/cyjoelchen/php-sweph/releases/tag/4.0.6
