### ISSUE TITLE
Missing 1 entry in swephp.stub.php

### ISSUE THREAD

**Issue by AstroSign-Dev** [kevindecapite/php-sweph#89]
In this section 1 entry for Nakshatra is missing in PHPStorm plugin:
Please add:
define('SE_SPLIT_DEG_NAKSHATRA', 1024);

// defines for function swe_split_deg(); (in swephlib.c);
define('SE_SPLIT_DEG_ROUND_SEC', 1);
define('SE_SPLIT_DEG_ROUND_MIN', 2);
define('SE_SPLIT_DEG_ROUND_DEG', 4);
define('SE_SPLIT_DEG_ZODIACAL', 8);
define('SE_SPLIT_DEG_KEEP_SIGN', 16); // don't round to next sign', e.g. 29.9999999 will be rounded to 29d59m59s (or 29d59m or 29d);
define('SE_SPLIT_DEG_KEEP_DEG', 32); // don't round to next degree e.g. 13.9999999 will be rounded to 13d59m59s (or 13d59m or 13d);

Thank you and Cheers
Werner

**Comment by kevindecapite** [comment]
@AstroSign-Dev Hi Werner, sorry for the delay responding. I've been taking time off for the holidays. I am happy to add this constant into the stub file.

First, would you be able to go through the SE docs and find any others that are missing?

I would prefer to do them all at once if possible. Thank you!

**Comment by kevindecapite** [comment]
PR:
- https://github.com/arcpointgroup/phpstorm-library-plugin/pull/3
