### ISSUE TITLE
HIndu astrology chart

### ISSUE THREAD

**Issue by vishalmehrait** [kevindecapite/php-sweph#91]
Is it possible to create hindu astrology chart with this library..?

**Comment by AstroSign-Dev** [comment]
Yes, with this library and some additional thinking, but yes it is possible as you can see on [my website astrosign.ch](https://www.astrosign.ch/berechnungen/horoskop-aszendent-nakshatra/)

**Comment by vishalmehrait** [comment]
phpize
./configure
make
sudo make install

phpize showing command not found. can you please help me with these
commands and how to use this library see screenshot

**Comment by AstroSign-Dev** [comment]
It seems you missed to install php-dev on your system.
A short Google search leads to that command:
sudo apt install php-dev
