### ISSUE TITLE
Altas Lookup

### ISSUE THREAD

**Issue by Vic-DiCara** [kevindecapite/php-sweph#96]
Does this include an atlas lookup? (it seems like it doesn't)

If no, what do you recommend for getting the lat, long, timezone, dst?

TY!

**Comment by AstroSign-Dev** [comment]
No Atlas Lookup included, I use Google Places and TimeZone API for that. Here is an [example on my Website](https://www.astrosign.ch/berechnungen/horoskop-aszendent-nakshatra/) on how I use it. Just click or tab in the field where "Ort suchen ..." is written then you can select the place and in the background I get timezone (including DST) and longitude and latitude. At least that works for me, but I know there are other choices also.
