### ISSUE TITLE
How to access \\wsl.localhost\Ubuntu-22.04\root\php-sweph from Apache2

### ISSUE THREAD

**Issue by Luc719** [kevindecapite/php-sweph#97]
Hello,

I am sorry for my ignorance, but everything ran well installing as described. I passed all the tests,  but I don't know how to access from Apache2 as I have all my scripts in \\wsl.localhost\Ubuntu-22.04\var\www\html that I access from localhost.

Thank your for you help,
Luc719

**Comment by kevindecapite** [comment]
@Luc719 It sounds like you installed the extension just fine. What happens when you call one of the Swiss Ephemeris functions from a PHP script? I recommend simply checking the version like this:

```php
<?php

echo swe_version();

```

**Comment by Luc719** [comment]
Hi kevin
rom http://localhost/swisseph/swe_version.php
I get nothing.



Note that my current scripts working with swetest are all working well.
Thank for your help,Lu 

    Le mercredi 9 août 2023 à 13:59:14 UTC+1, Kevin DeCapite ***@***.***> a écrit :  
 
 


@Luc719 It sounds like you installed the extension just fine. What happens when you call one of the Swiss Ephemeris functions from a PHP script? I recommend simply checking the version like this:
<?php

echo swe_version();

**Comment by Luc719** [comment]
Hi Kevin,
 with the script in my root apache2 server: /var/www/html/swe_version.php
<?php
echo swe_version();
?>

I get nothing (even though localhost is working fine with the other scripts.

![image](https://github.com/cyjoelchen/php-sweph/assets/141820811/da758cca-797d-4dd0-a67e-c752f44a3b85)

**Comment by kevindecapite** [comment]
You'll need to inspect your error logs to see what the problem is. Also check to make sure the extension is loaded by creating a page with:

```php
echo phpinfo();
```

You should see a section like the following image if it's loaded properly.
<img width="978" alt="Screenshot 2023-08-09 at 12 16 13 PM" src="https://github.com/cyjoelchen/php-sweph/assets/1189656/73f35b2c-e3c8-4891-8f8a-439bda32405c">

**Comment by Luc719** [comment]
Hello again,

The issue was resolved by Allen.
the file swephp.ini was missing in \\wsl.localhost\Ubuntu-22.04\etc\php\8.2\mods-available

file swephp.ini
; configuration for php common module
; priority=20
extension=swephp.so

Then activate the module with the command:
phpenmod swephp

restart Apache.

Et voilà ;)
